name: Hibajelenség
description: Elakadtál valamelyik demó vagy képzés gyakorlása kapcsán? Itt leírhatod a tapasztalt jelenséget.
title: "[I]: "
labels: ["issue", "cloud"]
assignees:
  - the1bit
body:
  - type: markdown
    attributes:
      value: |
        Köszöszönöm, hogy írsz. Írd le a jelenséget. Csatolj képet vagy hibaüzenetet is, hogy hamarabb találjunk megoldást számodra.
  - type: textarea
    id: what-happened
    attributes:
      label: Mi történt?
      description: Írd le azt is, melyik képzéssel vagy felhővel kapcsolatban kérdezel. Írd le részletesen a tapasztalt jelenséget. Térj ki arra is, hogyan lehet reprodukálni.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Témakör
      description: Melyik területen tapasztalsz nehézséget?
      options:
        - Azure
        - AWS
        - Google Cloud
        - IaC
        - Go lang
        - Docker
        - Kubernetes (AKS/EKS/GKE)
        - GitHub (Repository, Action, Settings)
        - AI (mesterséges intelligencia)
        - Egyéb technológia
    validations:
      required: true
  
