name: Kérdés
description: Általános kérdések felhővel vagy a képzéssel kapcsolatban
title: "[Q]: "
labels: ["question", "cloud"]
assignees:
  - the1bit
body:
  - type: markdown
    attributes:
      value: |
        Köszönöm, hogy írsz. Kérdezz bátran.
  - type: textarea
    id: what-happened
    attributes:
      label: Miben segíthetek?
      description: Írd le azt is, melyik képzéssel vagy felhővel kapcsolatban kérdezel.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Témakör
      description: Melyik terület?
      options:
        - Általános kérdés
        - Azure
        - AWS
        - Google Cloud
        - IaC
        - Go lang
        - Docker
    validations:
      required: true
  - type: checkboxes
    id: public-acknowledgment
    attributes:
      label: Nyilvánosság tudomásulvétele
      description: Az alábbi checkbox bejelölése kötelező a kérdés beküldéséhez.
      options:
        - label: "Tudomásul veszem, hogy minden itt megadott információ nyilvánosan elérhető, és bárki számára hozzáférhető, aki ezt a GitHub repository-t megnyitja."
          required: true
